### ISSUE TITLE
Post UWU Redesign Launch Checklist

### ISSUE THREAD

**Issue by crutchcorn** [unicorn-utterances/unicorn-utterances#830]
- [x] Merge PR
- [x] Verify website launch
- [x] Verify mailing list functionality
- [x] Verify ROBOTS.txt functionality
- [x] Verify RSS.XML functionality and validity
- [x] Verify sitemap.xml validity
- [x] Verify basic web.dev/measure perf metrics (we've eval'd regularly, just want to make sure nothing's wrong)

# Socials

- [x] Upload new profile picture/~~banner~~ on Twitter/X
- [x] Upload new profile picture/~~banner~~ on Mastodon
- [x] Upload new profile picture/banner on YouTube
- [x] Upload new profile picture/~~banner~~ on LinkedIn
- [x] Upload new profile picture/~~banner~~ on Facebook
- [x] Upload server banner to Discord
- [x] Upload server icon to Discord

# Announcements

- [x] Post Twitter thread with images
    - [x] Corbin to Quote RT with birthday mention
- [x] Post Mastodon thread with images
- [x] Post LinkedIn post with image
- [x] Post Facebook post with image
- [x] Send message to Discord announcements channel (`@everyone`?)
- [x] Send mailing list email?
